allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@arcjet/analyze-wasm@1.6.0'
  - '@arcjet/analyze@1.6.0'
  - '@arcjet/body@1.6.0'
  - '@arcjet/cache@1.6.0'
  - '@arcjet/duration@1.6.0'
  - '@arcjet/env@1.6.0'
  - '@arcjet/headers@1.6.0'
  - '@arcjet/ip@1.6.0'
  - '@arcjet/logger@1.6.0'
  - '@arcjet/nest@1.6.0'
  - '@arcjet/protocol@1.6.0'
  - '@arcjet/runtime@1.6.0'
  - '@arcjet/sprintf@1.6.0'
  - '@arcjet/stable-hash@1.6.0'
  - '@arcjet/transport@1.6.0'
  - arcjet@1.6.0
